#pragma once
#include "esphome/components/uart/uart.h"
#include "esphome/components/sensor/sensor.h"
#include "esphome/components/text_sensor/text_sensor.h"
#include "esphome/core/component.h"
#include "esphome/core/log.h"
#include <vector>

namespace esphome
{
    namespace pi18
    {

        class PI18Component : public PollingComponent, public uart::UARTDevice
        {
        public:
            // setters generated by codegen
            void set_grid_voltage_sensor(sensor::Sensor *s) { grid_voltage_ = s; }
            void set_grid_frequency_sensor(sensor::Sensor *s) { grid_frequency_ = s; }
            void set_ac_output_voltage_sensor(sensor::Sensor *s) { ac_output_voltage_ = s; }
            void set_ac_output_frequency_sensor(sensor::Sensor *s) { ac_output_frequency_ = s; }
            void set_output_apparent_power_sensor(sensor::Sensor *s) { output_apparent_power_ = s; }
            void set_output_active_power_sensor(sensor::Sensor *s) { output_active_power_ = s; }
            void set_load_percent_sensor(sensor::Sensor *s) { load_percent_ = s; }
            void set_battery_voltage_sensor(sensor::Sensor *s) { battery_voltage_ = s; }
            void set_battery_charge_current_sensor(sensor::Sensor *s) { battery_charge_current_ = s; }
            void set_battery_discharge_current_sensor(sensor::Sensor *s) { battery_discharge_current_ = s; }
            void set_battery_capacity_sensor(sensor::Sensor *s) { battery_capacity_ = s; }
            void set_heatsink_temperature_sensor(sensor::Sensor *s) { heatsink_temperature_ = s; }
            void set_pv1_power_sensor(sensor::Sensor *s) { pv1_power_ = s; }
            void set_pv1_voltage_sensor(sensor::Sensor *s) { pv1_voltage_ = s; }
            void set_mode_text_sensor(text_sensor::TextSensor *ts) { mode_text_ = ts; }

            void setup() override;
            void update() override;
            void dump_config() override;
            float get_setup_priority() const override { return setup_priority::DATA; }

        private:
            // sensors
            sensor::Sensor *grid_voltage_{nullptr};
            sensor::Sensor *grid_frequency_{nullptr};
            sensor::Sensor *ac_output_voltage_{nullptr};
            sensor::Sensor *ac_output_frequency_{nullptr};
            sensor::Sensor *output_apparent_power_{nullptr};
            sensor::Sensor *output_active_power_{nullptr};
            sensor::Sensor *load_percent_{nullptr};
            sensor::Sensor *battery_voltage_{nullptr};
            sensor::Sensor *battery_charge_current_{nullptr};
            sensor::Sensor *battery_discharge_current_{nullptr};
            sensor::Sensor *battery_capacity_{nullptr};
            sensor::Sensor *heatsink_temperature_{nullptr};
            sensor::Sensor *pv1_power_{nullptr};
            sensor::Sensor *pv1_voltage_{nullptr};
            text_sensor::TextSensor *mode_text_{nullptr};

            // helpers
            std::string build_command_(const std::string &cmd);
            bool read_line_(std::string &out, uint32_t timeout_ms);
            bool parse_gs_(const std::string &payload);
            void publish_mode_(uint8_t code);

            // pi18 CRC (16-bit). See protocol docs & open-source implementations.
            static uint16_t crc16_pi18_(const uint8_t *data, size_t len);
        };

    } // namespace pi18
} // namespace esphome
